### ISSUE TITLE
unable to save the model

### ISSUE THREAD

**Issue by Li-Yuanhang** [DatrikIntelligence/Stacked-DCNN-RUL-PHM21#1]
in the train_l1.py, train() function, after 
```
history = model.fit(train_gen, validation_data=test_gen, 
                            epochs=epochs, verbose=2, 
                            callbacks=[es, rlr, pr])
```
the later sentences 
```
history_path = os.path.join(cache_dir, 'cnn_history_%d.pk' % seed)
pk.dump(history.history, open(history_path, 'wb'))
model_path = os.path.join(cache_dir, 'cnn_l1_%d.h5' % seed)
model.save(model_path)
```
are not performed and directly returned to the for loop

I have installed the latest version of tensorflow with python3.9 intepreter, on the Windows 11 in pycharm

**Comment by run-si** [comment]
Have you fix it?

**Comment by dasolma** [comment]
Hello,
Sorry by the delay. 

Are you getting any king of error message?
